#import "@preview/bookly:3.1.0": *

#let abs = [
  The central challenge of any database management system is not merely the execution of queries, but the _efficient and persistent storage_ of the data upon which those queries operate. The question of how a table is stored on disk—how individual records are laid out within pages, and how those pages are assembled into a file—is not a low-level implementation detail. It is a strategic architectural decision that fundamentally determines the performance profile of every operation the system will perform. A shift in storage organization does not alter the logical result of a query, but it can transform its execution cost from logarithmic to linear, or from a fraction of a single I/O operation to half the read-write load of an entire file. The purpose of this discussion is to establish a rigorous _cost-model framework_ for understanding the primary storage organizations available to a database designer, to examine the precise trade-offs each entails, and to provide the analytical tools necessary for selecting the structure best suited to a given application workload.
]

#chapter(title: "Data Organization", abstract: abs, toc: true)[

  == Foundational Abstractions

  Before any analysis of file organizations can be meaningful, a set of foundational _abstractions_ must be established. These are the conceptual building blocks upon which all subsequent cost models depend.

  === Variable-Length Representation and the Record Identifier

  Historically, database systems relied on _fixed-size_ records. The length of every field was declared in the schema, and every record in a table was allocated an identical, pre-computed number of bytes. The position of any given field was trivially determined by a fixed offset from the record's start address. This model, however, proved fundamentally incompatible with the realities of _variable-length data_. Strings such as names, addresses, or unstructured text cannot be efficiently constrained to fixed widths without either wasteful padding or arbitrary truncation.

  Consequently, modern representations opt for variability. The record is internally organized with a compact header describing the number of fields it contains, followed by an offset array indicating the precise starting position of each field's value within the record body. This decouples the logical schema from any requirement for a fixed physical length. A critical consequence of this design is that an update modifying a field's value may alter the overall length of the record. A record that begins as relatively short can, after an update to a variable-length field, become significantly longer. The storage system must therefore accommodate _relocation_ within the page.

  This brings forth a concept of significant architectural importance: the _Record Identifier_ (_RID_) , and the requirement of its immutability. Every record within a database is uniquely addressed by a composite identifier—a pair consisting of a page identifier (_PID_) and a slot position within that page. The integrity of the entire indexing ecosystem depends on these identifiers remaining stable. Secondary indexes, which will be discussed in subsequent sessions, maintain persistent pointers to records through their RIDs. If a simple update operation were to change a record's identifier, every index referencing that record would be invalidated. This would make even trivial updates catastrophically expensive.

  The solution is an indirection layer inside the page. The RID does not point directly to the record's raw data bytes. Instead, it points to an entry in a _slot array_ stored at a fixed position in the page—typically at the header or footer. This array entry contains the actual current offset within the page where the record's data is currently located. When an update causes a record to grow beyond its original allocated space, the storage manager relocates the record to a different position within the same page where sufficient contiguous free space exists, and updates only the slot array entry. The externally visible RID, the identifier used by indexes and query cursors, remains entirely unaffected. This assumption of RID stability is maintained throughout the analysis that follows. If the record grows beyond the capacity of the current page and no sufficient free space is available within it, the storage manager relocates the record to a newly allocated page while preserving RID stability through the indirection provided by the slot array.

  === Files as Dynamically Growing Collections of Pages

  A _file_, in the database context, is a _logical sequence_ of pages. The most intuitive representation would appear to be a contiguous sequence of physical disk blocks. A file of one thousand pages could be mapped to one thousand consecutive sectors on the storage medium, making sequential access trivially efficient. However, this model is rendered impossible by the requirements of _dynamic growth_. When a file is first created empty, it would be fundamentally wasteful—and in practical systems, administratively untenable—to pre-allocate a vast contiguous extent of disk space for a file whose eventual size is unknown and likely to evolve over months or years of operation. No modern operating system or database system represents dynamic files as physically contiguous sequences.

  Two practical alternatives exist. The first models the file as a _linked list_, where each data page contains a pointer to the subsequent page in the logical sequence. A _doubly-linked variant_ enables both forward and backward scanning, a feature of particular value when data is kept sorted and queries involve descending order sorts. New pages can be inserted not only at the end of the file but, critically, in the middle. This flexibility proves essential for certain organizations that will be examined later.

  The second and more common approach is a _directory-based structure_. A separate, compact mapping table is maintained, recording the physical disk address of each logical page. The first page of the file is at address A, the second at address B, and so forth. While this directory is a separate structure, it is typically small enough to reside entirely in main memory, even for very large files. The analysis therefore operates under the assumption that locating any page by its logical number incurs zero additional disk I/O operations. The cost to read page 25 of a given file is simply the cost of a single read I/O to retrieve the data page itself.

  This model introduces an important performance observation. While the directory enables logically sequential access—page 1, then page 2, then page 3—the actual physical placement of these pages on the storage medium may be entirely non-sequential. Logical consecutiveness does not imply physical consecutiveness. On traditional rotating magnetic disks, this disparity carried a severe performance penalty due to _mechanical seek_ and _rotational latency_. Modern solid-state storage devices have rendered this concern far less significant, as access to any physical block incurs no mechanical delay. The principle, however, endures at the level of data transfer efficiency: unnecessary pages should not be read if they do not contain useful data. With these abstractions in place—variable-length records with stable identifiers, files as dynamic page collections with directory-based addressing—attention can now turn to the primary organizational strategies themselves.

  == Primary and Secondary organizations

  The design of any database system begins with a fundamental decision: how to physically arrange records on disk. This decision, known as the _primary organization_, determines the baseline performance characteristics that will govern every subsequent operation on the data. The central thesis of this chapter is that database file organization involves a fundamental tension between access speed, storage efficiency, and organizational flexibility. No single organization method is universally optimal; rather, each approach represents a distinct set of trade-offs that database designers must navigate based on their specific workload requirements.

  A database table possesses exactly one primary organization. This is the fundamental decision about where to physically place each new record as it arrives. When an insert command is executed, the primary organization—and nothing else—determines the page into which the record will be written. The choice is singular; one cannot maintain a table simultaneously sorted by family name and appended in arrival order. The primary organization might dictate placement at the end of the file, in the middle according to a sort key, or at a position determined by a hash function, but it must be exactly one such policy.

  After the primary organization has been decided, zero, one, or many _secondary organizations_ may be added. These are auxiliary data structures, most commonly indexes, whose sole function is to accelerate specific search and access patterns. A table stored with a heap primary organization—where records are appended in arrival order—can be augmented with a secondary B-tree index on a surname column. This index provides a fast, logarithmic-time path to locate records by surname, compensating for the heap's inherent weakness in selective searching. The distinction is of significant strategic importance: the primary organization determines properties such as insertion cost and table scan efficiency that cannot be mitigated after the fact by secondary structures. The secondary indexes are additive and optional. One can add them, drop them, or change them in response to evolving query patterns. The primary organization, once the table is populated, is extraordinarily expensive to change, as it requires rewriting every record according to a new layout policy. It is for this reason that the choice of primary organization is given such careful attention.

  A foundational insight that frames this entire discussion is that every organization different from the heap begins with a decision about which attribute's search performance to optimize. This means that database design starts with identifying which queries matter most, then selecting an organization that optimizes for those queries while accepting degradation for others. The choice of primary organization attribute represents a commitment that optimizes one access pattern at the expense of all others.

  == Static Versus Dynamic Organization

  A crucial conceptual framework distinguishes between _static_ and _dynamic_ organizations. Static organizations may require reorganization after many insertions or deletions, or potentially after every insertion. Dynamic organizations, by contrast, evolve locally with every single operation, but never require reorganization of the entire structure. This distinction has profound practical implications. Static organizations offer excellent performance during normal operation but require periodic "stop the world" events for reorganization. Dynamic organizations adapt incrementally to changes but often sacrifice some performance or storage efficiency during normal operation.

  == Heap Organization

  The simplest and most immediately intuitive primary organization is the so-called _heap_. The term carries different meanings across computer science domains—heaps in algorithm courses refer to specific in-memory tree-based structures—but within the context of storage organizations, it denotes a file where records are stored one after the other, strictly in the order they are inserted. The file begins empty, and every new record is simply appended to the last page.

  === Space Efficiency and the Table Scan

  The heap organization achieves the _theoretical ideal_ of space efficiency. The file contains no structural overhead beyond the records themselves. There are no gaps left for future insertions, no partially filled pages mandated by fill-factor policies, no index structures embedded within the data pages. The data density is effectively one hundred percent.

  This property has a direct and profound impact on the performance of the _table scan_, an operation defined as the sequential reading of every page in a file into the buffer pool. Table scans are far more common than is often assumed. A substantial fraction of query execution plans ultimately resort to scanning the entire contents of a table, whether because the query's predicate is insufficiently selective to warrant indexed access, or because the query accesses a majority of the table's columns, making index-only access inapplicable. Optimizing the table scan is therefore of genuine practical importance.

  When a heap file contains one gigabyte of logical data, the physical file on disk is precisely one gigabyte in size. A table scan thus transfers exactly one gigabyte of data from storage into memory. Contrast this with an organization that, for operational reasons examined later, maintains a fill factor of eighty percent. In such a structure, the same logical data would occupy approximately 1.25 gigabytes of physical storage, and a full table scan would incur a correspondingly longer transfer time. The principle is elegantly simple: space directly translates to time when entire files must be read. The heap organization, by minimizing space, inherently minimizes scan time. This is a property of the primary organization that no secondary index can replicate; even a perfectly tuned index cannot eliminate the cost of a full table scan when one is required.

  === Insertion Cost and Buffer Dynamics

  The insertion operation in a heap file carries a raw cost of 2 I/O operations. The system must locate the last page of the file, read it into the buffer pool, append the new record, and write the modified page back to disk. This baseline cost, however, bears little resemblance to the amortized cost experienced in practice, particularly under the load conditions typical of insert-heavy applications.

  The reason lies in _buffer pool dynamics_. In any system that performs frequent insertions into a particular table, the last page of that table's heap file becomes the single most frequently accessed page in the entire buffer pool. The buffer manager, implementing standard least-recently-used or clock-sweep replacement policies, will naturally retain this page in memory. The read I/O component of the insertion cost is therefore eliminated entirely under normal operating conditions; the page is already present in the buffer when the next insert arrives.

  The write I/O component is similarly subject to amortization. Consider a page that can contain, on average, one hundred records. When the first record is inserted into a newly allocated last page, the page becomes dirty—modified in memory but not yet written to disk. The buffer manager, following standard write-back policies, will not force this page to disk immediately. It will remain in the buffer, accumulating further inserts. Records two through one hundred are added to this same in-memory page, each insertion requiring no disk interaction whatsoever. Only when the hundred-and-first record arrives, necessitating the allocation of a new last page, does the buffer manager flush the now-full previous page to disk. The result is a single write I/O distributed across one hundred insertions. The amortized insertion cost is therefore approximately one divided by the page capacity in records—a value often on the order of $1/100$ of a single I/O.

  This property makes the heap organization the structure of choice for any workload where _insertion dominates_. The most illustrative example is the journal or event log—a table that records every significant action in the system, written to on every transaction, and read only in exceptional circumstances such as failure recovery or security audits. In such an environment, the heap's insertion cost, approaching an infinitesimal fraction of an I/O per record, is unmatched by any alternative primary organization.

  === The Cost of Search

  The advantage in insertion and scanning comes at a direct and severe cost for search operations. A heap file maintains no internal ordering of records. There is no structure that would allow the system to determine, without reading the data, which pages might contain records matching a given predicate.

  Consequently, an _equality search_—finding a specific record by a given key value—requires reading, at minimum, every page in the file that happens to contain records. Since the distribution of records across pages is determined solely by insertion order, and bears no relationship to any attribute values, a record with any given key value could reside on any page with equal probability. The system must therefore execute, in the worst and average case, a full table scan. For a file of one thousand pages, this means one thousand read I/O operations to locate a single record. The presence of multiple matching records offers no relief, as they may be _scattered_ across an arbitrarily large number of pages.

  The same analysis applies to _range search_ queries on any attribute. If a query requests all records where a salary falls between two values, the heap provides no means of identifying the pages where such records are stored without examining every page. The cost of the operation is therefore fully proportional to the size of the file, entirely independent of the number of records actually satisfying the predicate. Even the most selective query, returning a single record, incurs a scan of the entire data set.

  It is this catastrophic search performance that prevents the heap from being a universally ideal structure. The heap is supremely efficient for operations that write records or read them all, but it provides _no navigational support_ for operations that target specific subsets of the data. The strategic insight, which explains the heap's near-universal adoption as the default primary organization in modern DBMSs, is that this weakness is surgically addressable. Secondary indexes, added after the primary organization is chosen, can provide logarithmic-time access paths for equality and range searches. The insertion cost and table scan efficiency of a heap, by contrast, cannot be retrospectively improved by any secondary structure. A poorly chosen primary organization that hinders insertion or bloats table scan data transfer is a permanent liability. A heap with selective indexes added over time is a flexible, high-performance system that optimizes the irreducible operations at the primary level while delegating search acceleration to the secondary level.

  == Sequential Organization

  Where the heap abdicates any responsibility for ordering, the _sequential organization_ embraces it fully. In a sequential file, records are stored in sorted order according to the values of a single, designated attribute. This is not a secondary index that points to data stored elsewhere; it is the primary storage layout itself. The records, on the pages of the file, are physically ordered by, for example, family name.

  The benefits of this choice are most pronounced for two categories of operation: equality search and, far more significantly, range search.

  === Search Performance: Binary, Interpolation, and Clustering

  For an equality search, the sorted nature of the file permits navigation by _binary search_. The system reads the page at the midpoint of the file and examines the key value of some record on that page. If the target key is lower, the search continues recursively in the first half of the file; if higher, in the second half. Each probe halves the remaining search space. The resulting cost, in both the average and worst case, is logarithmic in the number of pages. A file of one thousand pages yields a worst-case search path of approximately ten page reads—a dramatic improvement over the heap's linear scan of one thousand reads.

  An even more aggressive technique is _interpolation search_. If the distribution of key values is known or can be reasonably approximated, the system can estimate the probable page location of the target key with far greater precision than a simple bisection. If the keys range from "AAA" to "ZZZ" and the target is "MMM," the system might begin its search not at the midpoint but approximately halfway through the file, where names around the midpoint of the alphabetical range would be expected to cluster. In practice, interpolation search can approach constant-time performance for well-distributed data, though its worst-case behavior _degrades when the data distribution is highly skewed_.

  Yet the truly distinguishing advantage of the sequential organization is not in finding a single record, but in finding a _contiguous range_ of them. This property is known as _clustering_. When records are stored sorted on a given attribute, all records whose values fall within a specific interval are physically adjacent to one another on a small, contiguous set of pages.

  The significance of this clustering effect is best illustrated with a concrete example. Consider a file containing one hundred million records distributed across one million pages, yielding an average of one hundred records per page. A range query with a _selectivity factor_ of 5%—meaning it is expected to return five million records—is executed against this table. If the records were stored in a heap, these five million records could plausibly be scattered across a substantial fraction of the entire file. The system might need to read hundreds of thousands, or even all one million, of the pages to retrieve them all (if there is no order, it actually has to read all pages). In the sequential organization, by contrast, the five million qualifying records occupy consecutive positions within the sorted order. At one hundred records per page, they will be contained entirely within fifty thousand consecutive pages. The cost of the range scan is therefore not proportional to the file size, nor to the number of result records, but to the number of pages that physically hold the result set. The very structure of the file has reduced the I/O cost by potentially an order of magnitude or more.

  #info-box([
    === Selectivity Factor

    Given a query applying a range predicate $phi = [a_1, a_2]$ on an attribute $A$ of a table $T$, the selectivity factor can be estimated as

    $ s_f (phi) = (a_2 - a_1) / (A_"max" - A_"min") $

    This estimation assumes that the values of $A$ are _uniformly distributed_ over the interval $[A_"min", A_"max"]$. While simple and computationally inexpensive, the estimate becomes inaccurate in the presence of skewed distributions, clustering, or significant outliers (e.g. Gaussian or multimodal distributions).
  ])

  === The Insertion Problem and Mitigation Strategies

  This clustering power is not free. Its cost is exacted on the insertion operation, which becomes, in the static sequential file, prohibitively expensive. To insert a new record into a sorted file, the system must first locate the correct insertion point. It must then make physical space for the new record on the appropriate page. If that page is full—or if the insertion of a single record would disrupt the sorted order of all subsequent records—every page after the insertion point must, in principle, be read and rewritten to shift the data down by one position. The average insertion affects approximately half the pages in the file. The _cost is therefore linear in the file size_, and for a large file, it is operationally unbearable.

  Several strategies exist to mitigate this issue, each with its own trade-off profile.

  The first is a _dynamic sequential organization_. Every page in the file is maintained with a _fill factor_ of, for example, 70%. A substantial fraction of each page is left deliberately empty. When an insert must be placed on a particular page, it can be accommodated locally, using the pre-reserved free space. Only infrequently, when a page's free space is eventually exhausted, is a split-and-redistribution operation required. The page's contents and the contents of an adjacent page are merged, split evenly, and redistributed, restoring the free space reserve. This approach localizes insertion costs to a small number of pages, achieving a bounded worst-case cost for individual insertions rather than the catastrophic $O(n)$ cost of the static variant.

  The trade-off is precisely the space efficiency so prized in the heap organization. The twenty or thirty percent of deliberately empty space on every page directly increases the physical size of the file, and correspondingly increases the cost of every full table scan. The same logical data now occupies more pages, and each scan must transfer proportionally more data from storage. This is not a trivial cost, and it is the primary reason the dynamic sequential organization is only considered when the application's query profile heavily favors range scans and the associated I/O savings on those operations outweigh the penalty on table scans.

  The second mitigation is a static sequential organization with a _differential file_, also known as a _delta approach_. The main file is maintained as a perfectly sorted, fully compacted sequential structure with no empty space reserved for future inserts. All new insertions are instead written into a small, separate heap file, the _delta file_, which is kept entirely in memory for fast access. A deletion is recorded as a record in a separate negative delta file, marking records in the main file as logically deleted without physically removing them.

  A search operation must consult all structures. It first checks the in-memory delta file; if the record is found there, the search is complete. It then checks the negative delta; if the record is marked as deleted, it is treated as absent. Only if the record is found in neither delta does the system proceed to execute a binary or interpolation search on the main sequential file. The search cost is marginally increased by the in-memory lookups, but those are negligible compared to disk access.

  The fundamental limitation of this approach is that the delta file grows over time. When it eventually exceeds the memory budget or reaches a size where its linear scan begins to dominate query costs, a _reorganization_ operation becomes mandatory. The system must merge the delta file, the negative delta file, and the main sequential file into a new, clean sequential file. This operation reads and writes both files in their entirety—a cost of two times the total number of pages. It is a "static" solution in the formal sense: every operation during normal runtime is efficient and bounded, but the system periodically incurs a massive, system-stopping reorganization cost. This approach is _suitable for datasets that are predominantly read-only_, with a manageable trickle of updates, such as reference data tables that are bulk-loaded periodically and then queried intensively.

]
